<?php include("header.php")?>
                
        <br /><h1 id="title"> Ocarina of Time </h1><br />
        
        <p id="game-description">É um jogo eletrônico de ação-aventura desenvolvido e publicado pela Nintendo EAD para o console Nintendo 64. Foi lançado no Japão em 21 de novembro de 1998; na América do Norte em 23 de novembro de 1998; e na Europa em 11 de dezembro do mesmo ano. Originalmente desenvolvido para o periférico Nintendo 64DD, o jogo foi ao invés lançado em cartuchos de 256-megabit (32-megabyte), os quais eram os cartuchos de maior capacidade que a Nintendo produzia na época. Ocarina of Time é o quinto jogo da série The Legend of Zelda, e o primeiro com gráficos 3D. 18 meses após seu lançamento, foi seguido pelo lançamento de uma sequência direta The Legend of Zelda: Majora's Mask.</p>
        <br />
        <p id="game-description">O jogador controla o heroi característico da série, Link, na terra de Hyrule. Link é enviado numa aventura para impedir Ganondorf, Rei da tribo dos Gerudo, de obter a Triforce, uma relíquia sagrada que garante os desejos de seu portador. Link viaja através do tempo e aventura-se através e várias masmorras para despertar os sábios ("sages", no original em inglês) que tem o poder de selar Ganondorf para sempre. A música é um fator chave para o progresso do jogo, uma característica também comum da série; o jogador deve aprender a tocar diversas músicas numa ocarina. O jogo foi o responsável por gerar um elevado interesse no próprio instrumento, além de mesmo aumento no número de vendas.</p>
        <br />
        <p id="game-description">Lançado para uma resposta critica arrebatadoramente positiva, a jogabilidade de Ocarina of Time introduziu características como o sistema de target lock system e os botcontext-sensitive buttons que se tornaram, desde então, elementos comuns aos jogos de aventura tridimensionais. Durante seu tempo de vida, Ocarina of Time vendeu mais de 1,14 milhões de cópias apenas no Japão, num total de mais de 7,6 milhões de cópias mundialmente. O jogo ganhou o Grande Prêmio na categoria de Artes Interativas do Japan Media Arts Festival, e ganhou seis prêmios no 2º Prêmio Anual Interactive Achievement Awards, incluindo o prêmio principal de Jogo do Ano.  O jogo é por vezes considerado, por jogadores e por críticos, como um dos melhores jogos eletrônicos já feitos. É atualmente o jogo mais bem avaliado no site agregador de criticas Metacritic, sendo o único com 99 pontos de um total de 100; e nas edições de 2008 e 2010, o Guinness World Records listou Ocarina of Time como o mais bem avaliado de todos os jogos que já foram avaliados.</p>
        <br />

<?php include("footer.php")?>